locale: "en-US"
title: "Junteng Liu"
title_separator: "-"
name: "Junteng Liu"
description: "Personal homepage of Junteng Liu"
url: "https://santion0001.github.io"
baseurl: "/LJT-Homepage"
repository: "santion0001/LJT-Homepage"

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

author:
  name: "Junteng Liu"
  bio: "First-year PhD candidate at HKUST NLP Group"
  email: "jliugi@connect.ust.hk"
  github: "Vicent0205"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  twitter: "junteng88716710"

compress_html:
  clippings: all
  ignore:
    envs: development

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - _drafts
  - _pages
  - _portfolio
  - _posts
  - _publications
  - _talks
  - _teaching
  - files
  - images
  - Dockerfile
  - Gemfile
  - LICENSE
  - README.md
  - docker-compose.yaml
  - markdown_generator
  - vendor
  - node_modules
  - tmp
  - log
